services:
  - type: web
    name: paper-bag-software
    runtime: python
    runtimeVersion: 3.12
    buildCommand: python3 -m venv /opt/render/project/.venv && /opt/render/project/.venv/bin/pip install -r requirements.txt
    startCommand: /opt/render/project/.venv/bin/gunicorn --bind 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PATH
        value: /opt/render/project/.venv/bin:/usr/local/bin:/usr/bin:/bin