services:
  - type: web
    name: paper-bag-software
    runtime: python
    runtimeVersion: 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PATH
        value: /opt/render/project/.venv/bin:/usr/local/bin:/usr/bin:/bin